version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: BankingApp
      DB_USERNAME: postgres
      DB_PASSWORD: ali123
      MAIL_USERNAME: your_email@gmail.com
      MAIL_PASSWORD: your_email_password
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: postgres-container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: BankingApp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ali123
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
