server:
  port: 8083
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    url: ${postgresql://postgres:yRGFYKpfTsKVwhrurdhaiXYvUaawRpyf@postgres.railway.internal:5432/railway} # Environment variable for database URL
    username: ${postgres} # Environment variable for database username
    password: ${yRGFYKpfTsKVwhrurdhaiXYvUaawRpyf} # Environment variable for database password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # Ensure this aligns with your database migration strategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME} # Environment variable for email username
    password: ${MAIL_PASSWORD} # Environment variable for email password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    com.online.banking.Back_End_Banking_System: DEBUG
  file:
    name: logs/application.log
